<?php

/**
 * Implements hook_theme().
 */
function lc_pages_theme($existing, $type, $theme, $path) {
    
    $vars = [
          'data_owner' => NULL,
          'data_owner_email' => NULL,
          'do_not_track' => NULL,
          'document_timestamp' => NULL,
          'site_name' => NULL,
          'email_accessibility' => NULL,
          'accessibility_date' => NULL,
          'accessibility_date_next' => NULL,
      ];
    
  return [
    'hpage_join_the_project' => [
      'variables' => []
    ],
    'hpage_privacy' => [
      'variables' => $vars,
    ],
    'hpage_cookies' => [
      'variables' => $vars,
    ],
    'hpage_accessibility_statement' => [
      'variables' => $vars,
    ],
  ];
}