<?php

/**
 * Implements hook_theme().
 */
function lc_zenodo_publications_theme($existing, $type, $theme, $path) {
  return [
    'publications_list' => [
        'variables' => [
            'publications' => NULL,
            'n_pubs' => NULL,
            'path_page' => NULL,
        ],
      'renderable' => TRUE,
      'template' => 'publications-list',
      'path' => \Drupal::service('extension.list.module')->getPath('lc_zenodo_publications') . '/templates',
    ]
  ];
}

